name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types: [completed]

env:
  UV_CACHE_DIR: /tmp/.uv-cache

jobs:
  cd:
    name: CD - Release Deployment
    runs-on: ubuntu-latest
    concurrency: cd-${{ github.ref }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false  # Disable built-in GitHub token

      - name: Authenticate with GH_PAT
        run: |
          git config --global user.email "admin@reid.ca"
          git config --global user.name "MountainGod2"
          echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Set Up UV Environment
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install Dependencies
        run: uv sync

      - name: Run Python Semantic Release
        id: release
        uses: python-semantic-release/python-semantic-release@v9
        with:
          github_token: '${{ secrets.GITHUB_TOKEN }}'

      # - name: Publish to TestPyPI
      #   if: steps.release.outputs.released == 'true'
      #   uses: pypa/gh-action-pypi-publish@v1.12.2
      #   with:
      #     repository-url: 'https://test.pypi.org/legacy/'
      #     attestations: false

      # - name: Test Install from TestPyPI
      #   if: steps.release.outputs.released == 'true'
      #   run: uv pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple my_pkg

      # - name: Publish to PyPI
      #   if: steps.release.outputs.released == 'true'
      #   uses: pypa/gh-action-pypi-publish@v1.12.2
